### ISSUE TITLE
Error on first opening

### ISSUE THREAD

**Issue by janeveraert** [kliptonize/encode#1]
Warning: scandir(application/helpers): failed to open dir: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/TAM_exploration/system/initialize/_Require.php on line 83

Warning: scandir(): (errno 2): No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/TAM_exploration/system/initialize/_Require.php on line 83

Warning: Invalid argument supplied for foreach() in /Applications/XAMPP/xamppfiles/htdocs/TAM_exploration/system/initialize/_Require.php on line 84

**Comment by janeveraert** [comment]
Fatal error: Class 'controllers\Index_Controller' not found in /Applications/XAMPP/xamppfiles/htdocs/TAM_exploration/system/initialize/_Routing.php on line 91

**Comment by kliptonize** [comment]
Yes, while upgrading to v 2.4 you'll need to change your controllernames and remove the `_Controller` suffix, as well as update your config-file for the landing controller to the correct name:
`define("LANDING_CONTROLLER", "Index_Controller");` to `define("LANDING_CONTROLLER", "Index");`

This should not happen again any time soon in the future, sorry!

**Comment by structief** [comment]
We're very sorry, both the issues should be solved with the latest commit/bugfix!
